version: '3'
services:
  redis:
    image: redis:6.2.5
    command: ["redis-server", "--save", "","--appendonly","no"]
    hostname: redis
    volumes:
      - ./data:/data
    restart: always
    ports:
      - 6379:6379
